[package]
name = "wl-tablet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raw-window-handle = "0.6.0"
softbuffer = "0.4.0"
wayland-backend = { version = "0.3.2", features = ["client_system"] }
wayland-client = "0.31.1"
wayland-protocols = { version = "0.31.0", features = ["client", "unstable"] }
winit = "0.29.7"
